// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idvwgrhddhvbtfptyxuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkdndncmhkZGh2YnRmcHR5eHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDk0ODUsImV4cCI6MjA3NDI4NTQ4NX0.1nn9t_Up6Jk9JkrJHF8TYaClrFKo19IJeBe4LGsPJhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});